---
cluster_name: prod
kubeconfig_path: "./kubeconfig.yaml"
k3s_version: v1.32.0+k3s1

networking:
  ssh:
    port: 22
    use_agent: true
    public_key_path: "~/.ssh/id_rsa.pub"
    private_key_path: "~/.ssh/id_rsa"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api:
      - 0.0.0.0/0

masters_pool:
  instance_type: cpx11
  instance_count: 3
  locations:
    - ash

worker_node_pools: []

protect_against_deletion: false

schedule_workloads_on_masters: true

create_load_balancer_for_the_kubernetes_api: true

local_path_storage_class:
  enabled: true

embedded_registry_mirror:
  enabled: false
