---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      imagePullSecrets:
        - name: imagepull-cred
      containers:
        - name: back
          image: docker.io/kirillsalykin/project
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: project.psql.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project.psql.credentials.postgresql.acid.zalan.do
                  key: password
          ports:
            - name: back
              containerPort: 5000
      volumes:
        - name: config
          configMap:
            name: config
