[package]
name = "project"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "project"

[dependencies]
tokio = { version = "1.44.0", features = ["full"] }

serde = { version = "1.0.209", features = ["derive"]}
serde_json = { version = "1.0.140" }

config = { version = "0.15.11", default-features = false, features = ["yaml"] }

sqlx = { version = "0.8.2", features = ["runtime-tokio", "macros", "postgres", "migrate", "uuid", "chrono" ] }

axum = { version = "0.8.1", features = ["macros", "json"] }
distilled = { git = "https://github.com/kirillsalykin/distilled", rev = "a35b37c", features = ["derive"] }
validator = { version = "0.20", default-features = false}
tower-http = { version = "0.6.2", features = ["cors", "timeout"] }

anyhow = {version = "1.0.97"}
thiserror = {version = "2.0.12"}
bcrypt = {version= "0.17.0"}
uuid = { version = "1.16.0", features = ["v7", "serde"] }
