server {
    listen 80;
    server_name localhost;

    # Site (static HTML)
    location / {
        root /usr/share/nginx/html/site;
        index index.html;
        try_files $uri $uri.html $uri/ /index.html;
    }

    # App
    location /app {
        alias /usr/share/nginx/html/app;
        index index.html;
        try_files $uri $uri/ /app/index.html;
    }
} 