server {
    listen       80;
    server_name  localhost;

    location /app/ {
        try_files $uri $uri/ /app/index.html;
    }

    location /site/ {
        try_files $uri $uri/ /site/index.html;
    }

    location / {
        try_files $uri $uri/ /site/;
    }
}
