apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: psql
  namespace: default
spec:
  teamId: "default"
  numberOfInstances: 3
  volume:
    size: 20Gi
    storageClass: "local-path"
  users:
    project:
      - superuser
  databases:
    project: project
  postgresql:
    version: "17"
