apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: psql
  namespace: db
spec:
  teamId: "acid"
  numberOfInstances: 1
  volume:
    size: 1Gi
  users:
    zalando:
      - superuser
  databases:
    foo: zalando
  postgresql:
    version: "17"
