---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      imagePullSecrets:
        - name: imagepull-cred
      containers:
        - name: front
          image: docker.io/kirillsalykin/project
          ports:
            - name: front
              containerPort: 80
