apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: docker.io/kirillsalykin/project
    newTag: "front-9" # {"$imagepolicy": "flux-system:front:tag"}
