---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-cred-20ec9715
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgB2qAE2Ofv5OepDUoLqyC1g+QG74FwBzHW31h5yjJ+Ic+jciNSCAY+fHczcld2XsNxDQ2qdS/PdKlgrQBtU+t8fcSUyn/NgaJuOCKHoZCPyetA1XK9gfKFBFFinrS1z4hyRd0C+u7AbFHzrkvMcCgcSAl4BYFGpNYPTpEFVgmISCwuR/kJHupnEy6F6l5IgWQotuHGOSif2TZX+6b6zz3v0DzFlvnjbs297G6REnvCCGvLqjk6TmEma5F/quXwkPf2AF9HbH62SmWAiQZhzpcozoTMMt1dFT1U4XXWplLd24OQGadyzt00ZwQb2PuU3vdRG2F0oWTt0w2T6JkbNwu50JOB5q0AfQWpx40uzKXUO0fPXGXOvpRq9vomwF0fHyviHqUNUfoO12Xn24uN8jK3O8DR0SgDZeBxH7kmAep1ui3/j8CFYkbk5QaMfNncSmajMqn6CfFAxApQD7UNlRpFj7T7TeyuSmc4rzGcD27iGD0Ow6TVAG/s3MmX00czBhTBUSrBLlnzQ3RAhg6u2QgzCiPg88FiNC1Nid8soqTrhmLgTDmAv25hwUN/QGO5ZxyHJjzFC5HiCVRNFEHgAtWogE+9am7C5EsKJxPC+EioS6KFMpI2tCwez4CHAwYHQrrIrn4l+GftVDMhMj/5M4tS7Us+BpN3P8Bd4afUhfCb3N8T2dD0mz6ZI2JRxkdz3iAJNDyQbP5VKdkNQrpxOz/SRXMMgyoL9OXUyli8RQT6Mnwc6E5lqX9Mji24HxIY8i3iSLM5FRt+WUHyReZHaPMaXHNQ0F1YUFJqfEZUWVLuj+Zqz0YqQUGVhR35zi/fwrTa7cRYb++BJGeHwhxtQ9G1hy1wLiFu+SgsLTH9rZgR3gWv48t4tMHIsggmO+ih5p4P4coAgMVZ2UeSx11nAal+cTIy8Eg==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-cred-20ec9715
      namespace: default
    type: kubernetes.io/dockerconfigjson
