---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: imagepull-cred-20ec9715
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCtM66Dzqxv3odtDWkMPW9mxcy4x7WZH8JrfT+s8h3819DaTY3TWaTgphbQi+OSHABPtyc+z9JElKgUPTgv9KSYRFWH7Wh/KwwIZxatyuRfS465W+thWpl6CuhkoWILWdvq8R1RwY0AMCFncabGJsJ0VIY2Xt7ikhWGEd6mA8vExJYQkx8oOehViVne9tXbGhLpTgyLcKGilwII7m+c8UNSobcWoMMUIofBVtMkGdG90f6lGhnM6jcBuace5aMi1w9v9/QIqsQIBgTaWP/k6UhJ5J2yMZ+aQT244Ol0dIMa/U0FS9zty1anKWk01quu+YSQRASmrrL1pPAvEp8WJDHwro2AcaVDnl0APTJ5PiFwa8OWgsyJZajSyEuINL4DsqcNAyomsL1dn6yTJn/fJK1XfkemR4QQKFtG/USH2qxFxAxuz5VMphY4IbsGWZ0kUorcJ7IK98d2GZ59ZqWBxYXHGEdJnMOvCvw20xfKnE9PBkcIVASd6srSI28HCSSH26lkDzxP73LIXuLUJ3n0IkXfrhck7vnlXlg7TbUkUTsK0b0DeXoCUK9pAjbGFrzaZLqwriqVHgmr7L180H/mu5qTEVfn0cK4OOTsD28tAR8KyLk5ir/+q91211E5MzeiXKwVGKm7us641gI5IE3MQ8gebFawTOswMmglS/OPch4eOraSrZ4v6lzaXHBO34TYkjJtSx5Onhdhsgkbn/aWmWbimyPPnou64ivb3QDVcbbaj1e626Z6ZKLTIZ+xGVangQpZKlA2NPZkC4mqrgMM9SWsltL+zLs36WHj9XKTNXpC1ssc4e/Yzdf456W04e+vtrlkQ9ga27uWbKbBjPlPHWQmg8i7a8pNzVayRQ89yg54TuX3PdTuq8PmpzxqtFas6qIcwS1XnucJycIyCjkzS1DEl4Vgrw==
  template:
    metadata:
      creationTimestamp: null
      name: imagepull-cred-20ec9715
      namespace: default
    type: kubernetes.io/dockerconfigjson
