---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: imagepull-cred-8d1fddce
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAbxf/h1sU396P3BZckNRNnIQgH4nESEm5ahYew24PwvnGTvuPBghe54lM30B09Lw7XRM7RU2TdTFugWJcR/VYQV5nLOhVdEhtP69xSQPjQQ9rFg3QMWytgmZjCPamaHSHIsIPJZtqZc6IXvYzdEkdx5E9mzui5PQyoYdUKb+9vr7FtBUoBgXyXl2nfJboY0gfAT3T3IRklAg6pIaOkrqPqeIEyDUZ0S1MTWKwx2Z4pTf2UkiwTQvA2ngXcCPhnX2skUHpjmduxT474EKgp1mOtGJylbR8xMsy865MbBNm11HRnuI69g4rchWh3NDpSoPWmU2coZz70w3l08IAiTCzyI9XY/Nf/8XpXPgcoofpukJu1XTLEQr7rSJZQbSltqn7Da+RXO6ds0prdSrpMIgluTwIejejBTFLd4Nw2BsaSTp6HF2LG1dnCUxMZ3Dd+H2874AeHiefN7oPDU2CLMJbz+A2fcyGA3rM+jwbsb9riUQgTN3vB2g5JYz9tdatNgBMgQlDiC9CFbXAJhgf7tXIgd24IiuzZLNSnWdTfUUPH3SApAnb2A9IvX5u6Ffi4VymrrD52e9kozB6EXmH0tlnIVGzdDQA3mENapvvNg+fAOTIgAKPhP9kbo6zIU+xWAFA0fNhPxKFHgwZU+2OrVnqRWfM9ZhxoPjGRh2D3eynEFsbRuJhYQlbwCpFjyPCnUiFQrzFhr+8evg8hjeaTjg3OQ6O81U/VNS5VtwZm12hldsAzivdt9kw6mGvqkKOKLT14I/fhtNljrbaM0hJF7xknRC+YCEQAZ2PxXMkkXrHM4/nveEuqhpLHtZcHdGXlnC4HtUQBZHfksa7aGn5B5eLWDjPYzRJEzpA8
  template:
    metadata:
      creationTimestamp: null
      name: imagepull-cred-8d1fddce
      namespace: default
    type: kubernetes.io/dockerconfigjson
