---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: backend
  namespace: flux-system
spec:
  image: docker.io/kirillsalykin/project
  interval: 1m0s
  secretRef:
    name: dockerhub-cred-20ec9715
