# .github/workflows/build-and-push-be.yml
name: Build, Cache & Push BE Image

on:
  push:
    tags:
      - 'be-*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache cargo registry & git
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-deps-{{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build output
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}

      - name: Build project binary
        run: cargo build --release --locked

      - name: Build & push BE image
        uses: docker/build-push-action@v5
        with:
          context: back
          file: back/Dockerfile
          push: true
          tags: kirillsalykin/project:${{ github.ref_name }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
